#include <furi.h>
#include <furi_hal.h>
#include <dialogs/dialogs.h>
#include <gui/gui.h>
#include <gui/modules/text_input.h>
#include <gui/view.h>
#include <gui/view_holder.h>
#include <input/input.h>
#include <lfrfid/lfrfid_dict_file.h>
#include <lfrfid/lfrfid_worker.h>
#include <storage/storage.h>
#include <stdlib.h>
#include <string.h>
#include <toolbox/protocols/protocol_dict.h>

/* generated by fbt from .png files in images folder */
#include <my_rfid_keys_icons.h>

#define TAG "MyRfidKeys"
#define MY_RFID_KEYS_FOLDER EXT_PATH("apps_data/my_rfid_keys")
#define MY_RFID_KEYS_SCAN_TIMEOUT_MS (30 * 1000)
#define MY_RFID_KEYS_SPLASH_MS (5 * 1000)
#define MY_RFID_KEYS_SUCCESS_MS (5 * 1000)
#define MY_RFID_KEYS_READ_DONE (1U << 0)
#define MY_RFID_KEYS_WRITE_DONE (1U << 1)
#define MY_RFID_KEYS_PASSWORD_DONE (1U << 2)
#define MY_RFID_KEYS_PASSWORD_MAX_LEN 32
#define MY_RFID_KEYS_FILENAME_MAX_LEN 48
#define MY_RFID_KEYS_ENCRYPTED_MAGIC "MRK2"
#define MY_RFID_KEYS_AES_IV_SIZE 12
#define MY_RFID_KEYS_MAX_FILE_SIZE (16 * 1024)

typedef enum {
    MyRfidKeysViewMain,
    MyRfidKeysViewTextInput,
} MyRfidKeysView;

typedef enum {
    MyRfidKeysViewSplash,
    MyRfidKeysViewMenu,
    MyRfidKeysViewScanning,
    MyRfidKeysViewReadSuccess,
    MyRfidKeysViewPassword,
    MyRfidKeysViewEncrypting,
    MyRfidKeysViewDecrypting,
    MyRfidKeysViewWorking,
    MyRfidKeysViewOpening,
    MyRfidKeysViewDeleting,
    MyRfidKeysViewConfirmDelete,
    MyRfidKeysViewAbout,
    MyRfidKeysViewEmulating,
    MyRfidKeysViewSaved,
    MyRfidKeysViewSaveError,
    MyRfidKeysViewTimeout,
    MyRfidKeysViewCancelled,
} MyRfidKeysViewState;

typedef struct {
    FuriEventFlag* events;
    ProtocolId protocol;
} MyRfidKeysReadContext;

typedef struct {
    FuriMessageQueue* input_queue;
    FuriString* line_1;
    FuriString* line_2;
    FuriEventFlag* events;
    char password[MY_RFID_KEYS_PASSWORD_MAX_LEN + 1];
    char filename_input[MY_RFID_KEYS_FILENAME_MAX_LEN + 1];
    uint8_t menu_index;
    bool file_open;
    ProtocolId loaded_protocol;
    MyRfidKeysViewState state;
    ViewHolder* view_holder;
    View* main_view;
    TextInput* text_input;
} MyRfidKeysApp;

typedef enum {
    MyRfidKeysMenuRead,
    MyRfidKeysMenuOpen,
    MyRfidKeysMenuDelete,
    MyRfidKeysMenuEmulate,
    MyRfidKeysMenuClose,
    MyRfidKeysMenuAbout,
    MyRfidKeysMenuExit,
} MyRfidKeysMenuItem;

static bool my_rfid_keys_has_open_file(const MyRfidKeysApp* app) {
    return app->file_open && app->loaded_protocol != PROTOCOL_NO;
}

static uint8_t my_rfid_keys_menu_count(const MyRfidKeysApp* app) {
    return my_rfid_keys_has_open_file(app) ? 4 : 5;
}

static MyRfidKeysMenuItem my_rfid_keys_menu_item_at(const MyRfidKeysApp* app, uint8_t index) {
    if(my_rfid_keys_has_open_file(app)) {
        if(index == 0) return MyRfidKeysMenuEmulate;
        if(index == 1) return MyRfidKeysMenuClose;
        if(index == 2) return MyRfidKeysMenuAbout;
        return MyRfidKeysMenuExit;
    }

    if(index == 0) return MyRfidKeysMenuRead;
    if(index == 1) return MyRfidKeysMenuOpen;
    if(index == 2) return MyRfidKeysMenuDelete;
    if(index == 3) return MyRfidKeysMenuAbout;
    return MyRfidKeysMenuExit;
}

static const char* my_rfid_keys_menu_label(MyRfidKeysMenuItem item) {
    if(item == MyRfidKeysMenuRead) return "Add Key";
    if(item == MyRfidKeysMenuOpen) return "Open";
    if(item == MyRfidKeysMenuDelete) return "Delete Key";
    if(item == MyRfidKeysMenuEmulate) return "Emulate";
    if(item == MyRfidKeysMenuClose) return "Close File";
    if(item == MyRfidKeysMenuAbout) return "About";
    return "Exit";
}

static void my_rfid_keys_view_update(MyRfidKeysApp* app) {
    view_commit_model(app->main_view, true);
}

static MyRfidKeysApp* my_rfid_keys_get_view_app(void* model) {
    return *((MyRfidKeysApp**)model);
}

static void my_rfid_keys_draw_callback(Canvas* canvas, void* model) {
    MyRfidKeysApp* app = my_rfid_keys_get_view_app(model);
    const char* hourglass_frames[] = {"|", "/", "-", "\\"};

    canvas_clear(canvas);
    canvas_set_color(canvas, ColorBlack);
    canvas_set_font(canvas, FontPrimary);

    if(app->state == MyRfidKeysViewSplash) {
        canvas_draw_icon(canvas, 32, 0, &I_splash_64x32);
        canvas_draw_str_aligned(canvas, 64, 43, AlignCenter, AlignCenter, "My RFID Keys");
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str_aligned(canvas, 64, 58, AlignCenter, AlignCenter, "Encrypted tag vault");
    } else if(app->state == MyRfidKeysViewMenu) {
        canvas_draw_str_aligned(canvas, 64, 10, AlignCenter, AlignCenter, "My RFID Keys");
        canvas_set_font(canvas, FontSecondary);
        const uint8_t menu_count = my_rfid_keys_menu_count(app);
        const uint8_t start_y = menu_count == 5 ? 18 : 24;
        const uint8_t step_y = menu_count == 5 ? 11 : 12;
        for(uint8_t i = 0; i < menu_count; i++) {
            const uint8_t y = start_y + (i * step_y);
            canvas_draw_str(canvas, 18, y, app->menu_index == i ? ">" : " ");
            canvas_draw_str(canvas, 30, y, my_rfid_keys_menu_label(my_rfid_keys_menu_item_at(app, i)));
        }
    } else if(app->state == MyRfidKeysViewScanning) {
        canvas_draw_str_aligned(canvas, 64, 18, AlignCenter, AlignCenter, "Scan RFID");
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str_aligned(canvas, 64, 40, AlignCenter, AlignCenter, "Hold a LF tag near the back");
        canvas_draw_str_aligned(canvas, 64, 56, AlignCenter, AlignCenter, "Back: cancel");
    } else if(app->state == MyRfidKeysViewReadSuccess) {
        canvas_draw_icon(canvas, 40, 2, &I_success_48x32);
        canvas_draw_str_aligned(canvas, 64, 48, AlignCenter, AlignCenter, "Success");
    } else if(app->state == MyRfidKeysViewEncrypting || app->state == MyRfidKeysViewDecrypting ||
              app->state == MyRfidKeysViewWorking) {
        const uint8_t frame = (furi_get_tick() / furi_ms_to_ticks(150)) % COUNT_OF(hourglass_frames);
        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str_aligned(canvas, 64, 18, AlignCenter, AlignCenter, hourglass_frames[frame]);
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str_aligned(
            canvas, 64, 38, AlignCenter, AlignCenter, furi_string_get_cstr(app->line_1));
        canvas_draw_str_aligned(
            canvas, 64, 54, AlignCenter, AlignCenter, furi_string_get_cstr(app->line_2));
    } else if(app->state == MyRfidKeysViewOpening) {
        canvas_draw_str_aligned(canvas, 64, 24, AlignCenter, AlignCenter, "Open File");
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str_aligned(canvas, 64, 44, AlignCenter, AlignCenter, "Choose an .erfid file");
    } else if(app->state == MyRfidKeysViewDeleting) {
        canvas_draw_str_aligned(canvas, 64, 24, AlignCenter, AlignCenter, "Delete Key");
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str_aligned(canvas, 64, 44, AlignCenter, AlignCenter, "Choose an .erfid file");
    } else if(app->state == MyRfidKeysViewConfirmDelete) {
        canvas_draw_str_aligned(canvas, 64, 8, AlignCenter, AlignCenter, "Are you SURE?");
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str_aligned(canvas, 64, 25, AlignCenter, AlignCenter, "This file will be");
        canvas_draw_str_aligned(canvas, 64, 38, AlignCenter, AlignCenter, "permanently deleted.");
        canvas_draw_str(canvas, 8, 60, "< No");
        canvas_draw_str_aligned(canvas, 120, 60, AlignRight, AlignBottom, "Yes >");
    } else if(app->state == MyRfidKeysViewAbout) {
        canvas_draw_str_aligned(canvas, 64, 22, AlignCenter, AlignCenter, "My RFID Keys");
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str_aligned(canvas, 64, 42, AlignCenter, AlignCenter, "\xC2\xA9 Kevin W Brown 2026");
        canvas_draw_str_aligned(canvas, 64, 58, AlignCenter, AlignCenter, "Back: menu");
    } else if(app->state == MyRfidKeysViewSaved) {
        canvas_draw_icon(canvas, 40, 0, &I_success_48x32);
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str_aligned(
            canvas, 64, 43, AlignCenter, AlignCenter, furi_string_get_cstr(app->line_1));
        canvas_draw_str_aligned(
            canvas, 64, 58, AlignCenter, AlignCenter, furi_string_get_cstr(app->line_2));
    } else {
        canvas_draw_str_aligned(
            canvas, 64, 14, AlignCenter, AlignCenter, furi_string_get_cstr(app->line_1));
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str_aligned(
            canvas, 64, 34, AlignCenter, AlignCenter, furi_string_get_cstr(app->line_2));
        canvas_draw_str_aligned(canvas, 64, 56, AlignCenter, AlignCenter, "Back: menu");
    }
}

static void my_rfid_keys_flush_input(MyRfidKeysApp* app) {
    InputEvent event;

    while(furi_message_queue_get(app->input_queue, &event, 0) == FuriStatusOk) {
    }
}

static bool my_rfid_keys_is_button_press(const InputEvent* event) {
    return event->type == InputTypeShort;
}

static bool my_rfid_keys_input_callback(InputEvent* event, void* context) {
    MyRfidKeysApp* app = context;
    furi_message_queue_put(app->input_queue, event, FuriWaitForever);
    return true;
}

static void my_rfid_keys_read_callback(
    LFRFIDWorkerReadResult result,
    ProtocolId protocol,
    void* context) {
    MyRfidKeysReadContext* read_context = context;

    if((result == LFRFIDWorkerReadDone) && (protocol != PROTOCOL_NO)) {
        read_context->protocol = protocol;
        furi_event_flag_set(read_context->events, MY_RFID_KEYS_READ_DONE);
    }
}

static bool my_rfid_keys_ensure_folder(Storage* storage) {
    const FS_Error mkdir_result = storage_common_mkdir(storage, MY_RFID_KEYS_FOLDER);

    return mkdir_result == FSE_OK || mkdir_result == FSE_EXIST;
}

static void my_rfid_keys_build_filename(FuriString* filename, const char* extension) {
    DateTime datetime;
    furi_hal_rtc_get_datetime(&datetime);

    furi_string_printf(
        filename,
        MY_RFID_KEYS_FOLDER "/RFID_%04u%02u%02u_%02u%02u%02u_%lu.%s",
        datetime.year,
        datetime.month,
        datetime.day,
        datetime.hour,
        datetime.minute,
        datetime.second,
        furi_get_tick(),
        extension);
}

static void my_rfid_keys_build_named_filename(FuriString* filename, const char* name) {
    furi_string_printf(filename, MY_RFID_KEYS_FOLDER "/%s.erfid", name);
}

static void my_rfid_keys_sanitize_filename(char* filename) {
    const size_t len = strlen(filename);
    const char extension[] = ".erfid";

    if(len > strlen(extension) && strcmp(filename + len - strlen(extension), extension) == 0) {
        filename[len - strlen(extension)] = '\0';
    }

    for(char* cursor = filename; *cursor; cursor++) {
        const char c = *cursor;
        if(c == '/' || c == '\\' || c == ':' || c == '*' || c == '?' || c == '"' || c == '<' ||
           c == '>' || c == '|') {
            *cursor = '_';
        }
    }

    while(filename[0] == '.') {
        filename[0] = '_';
    }
}

static const char* my_rfid_keys_basename(const char* path) {
    const char* name = strrchr(path, '/');
    return name ? name + 1 : path;
}

static void my_rfid_keys_show_working(MyRfidKeysApp* app, const char* action, const char* filename) {
    app->state = MyRfidKeysViewWorking;
    furi_string_set(app->line_1, action);
    furi_string_set(app->line_2, my_rfid_keys_basename(filename));
    my_rfid_keys_view_update(app);
    furi_delay_ms(120);
}

static void my_rfid_keys_show_done(MyRfidKeysApp* app, const char* action, const char* filename) {
    app->state = MyRfidKeysViewSaved;
    furi_string_set(app->line_1, action);
    furi_string_set(app->line_2, my_rfid_keys_basename(filename));
}

static bool my_rfid_keys_wait_for_read(
    MyRfidKeysApp* app,
    FuriEventFlag* events,
    View* view) {
    UNUSED(view);
    const uint32_t start_tick = furi_get_tick();
    InputEvent event;

    app->state = MyRfidKeysViewScanning;
    furi_string_reset(app->line_1);
    furi_string_reset(app->line_2);
    my_rfid_keys_view_update(app);

    while(true) {
        const uint32_t flags =
            furi_event_flag_wait(events, MY_RFID_KEYS_READ_DONE, FuriFlagWaitAny, 100);
        if(!(flags & FuriFlagError) && (flags & MY_RFID_KEYS_READ_DONE)) {
            return true;
        }

        if(furi_get_tick() - start_tick >= furi_ms_to_ticks(MY_RFID_KEYS_SCAN_TIMEOUT_MS)) {
            app->state = MyRfidKeysViewTimeout;
            furi_string_set(app->line_1, "No Tag Found");
            furi_string_set(app->line_2, "Scan timed out");
            return false;
        }

        if(furi_message_queue_get(app->input_queue, &event, 100) == FuriStatusOk) {
            if(my_rfid_keys_is_button_press(&event) && event.key == InputKeyBack) {
                app->state = MyRfidKeysViewCancelled;
                furi_string_set(app->line_1, "Cancelled");
                furi_string_set(app->line_2, "Nothing was saved");
                return false;
            }
        }
    }
}

static bool my_rfid_keys_wait_for_menu(MyRfidKeysApp* app, View* view, MyRfidKeysMenuItem* item) {
    UNUSED(view);
    InputEvent event;

    app->state = MyRfidKeysViewMenu;
    app->menu_index = 0;
    my_rfid_keys_view_update(app);

    while(true) {
        if(furi_message_queue_get(app->input_queue, &event, FuriWaitForever) != FuriStatusOk) {
            continue;
        }

        if(!my_rfid_keys_is_button_press(&event)) {
            continue;
        }

        if(event.key == InputKeyBack) {
            return false;
        } else if(event.key == InputKeyUp) {
            if(app->menu_index > MyRfidKeysMenuRead) {
                app->menu_index--;
            }
        } else if(event.key == InputKeyDown) {
            if(app->menu_index < my_rfid_keys_menu_count(app) - 1) {
                app->menu_index++;
            }
        } else if(event.key == InputKeyOk) {
            *item = my_rfid_keys_menu_item_at(app, app->menu_index);
            return true;
        }

        my_rfid_keys_view_update(app);
    }
}

static void my_rfid_keys_wait_for_exit(MyRfidKeysApp* app) {
    InputEvent event;

    while(true) {
        if(furi_message_queue_get(app->input_queue, &event, FuriWaitForever) == FuriStatusOk) {
            if(my_rfid_keys_is_button_press(&event) && event.key == InputKeyBack) {
                break;
            }
        }
    }
}

static void my_rfid_keys_show_about(MyRfidKeysApp* app) {
    app->state = MyRfidKeysViewAbout;
    my_rfid_keys_view_update(app);
    my_rfid_keys_wait_for_exit(app);
    app->state = MyRfidKeysViewMenu;
}

static void my_rfid_keys_password_callback(void* context) {
    MyRfidKeysApp* app = context;
    furi_event_flag_set(app->events, MY_RFID_KEYS_PASSWORD_DONE);
}

static void my_rfid_keys_back_callback(void* context) {
    MyRfidKeysApp* app = context;

    if(app->state == MyRfidKeysViewPassword) {
        app->password[0] = '\0';
        furi_event_flag_set(app->events, MY_RFID_KEYS_PASSWORD_DONE);
    }
}

static bool my_rfid_keys_ask_text(
    MyRfidKeysApp* app,
    View* view,
    MyRfidKeysViewState state,
    const char* header,
    char* buffer,
    size_t buffer_size) {
    UNUSED(view);

    buffer[0] = '\0';
    furi_event_flag_clear(app->events, MY_RFID_KEYS_PASSWORD_DONE);
    text_input_reset(app->text_input);
    text_input_set_header_text(app->text_input, header);
    text_input_set_result_callback(
        app->text_input,
        my_rfid_keys_password_callback,
        app,
        buffer,
        buffer_size,
        true);
    text_input_set_minimum_length(app->text_input, 1);
    app->state = state;
    view_holder_set_view(app->view_holder, text_input_get_view(app->text_input));

    while(true) {
        const uint32_t flags =
            furi_event_flag_wait(app->events, MY_RFID_KEYS_PASSWORD_DONE, FuriFlagWaitAny, 100);
        if(!(flags & FuriFlagError) && (flags & MY_RFID_KEYS_PASSWORD_DONE)) {
            if(buffer[0] == '\0') {
                app->state = MyRfidKeysViewCancelled;
                furi_string_set(app->line_1, "Cancelled");
                furi_string_set(app->line_2, "Nothing was saved");
                view_holder_set_view(app->view_holder, app->main_view);
                my_rfid_keys_view_update(app);
                return false;
            }

            view_holder_set_view(app->view_holder, app->main_view);
            return true;
        }

        InputEvent event;
        if(furi_message_queue_get(app->input_queue, &event, 0) == FuriStatusOk) {
            if(my_rfid_keys_is_button_press(&event) && event.key == InputKeyBack) {
                app->state = MyRfidKeysViewCancelled;
                furi_string_set(app->line_1, "Cancelled");
                furi_string_set(app->line_2, "Nothing was saved");
                view_holder_set_view(app->view_holder, app->main_view);
                my_rfid_keys_view_update(app);
                return false;
            }
        }
    }
}

static bool my_rfid_keys_ask_filename(MyRfidKeysApp* app, View* view, FuriString* filename) {
    if(!my_rfid_keys_ask_text(
           app,
           view,
           MyRfidKeysViewPassword,
           "Filename",
           app->filename_input,
           sizeof(app->filename_input))) {
        return false;
    }

    my_rfid_keys_sanitize_filename(app->filename_input);
    my_rfid_keys_build_named_filename(filename, app->filename_input);
    return true;
}

static bool my_rfid_keys_ask_password(MyRfidKeysApp* app, View* view) {
    if(!my_rfid_keys_ask_text(
           app, view, MyRfidKeysViewPassword, "Password", app->password, sizeof(app->password))) {
        return false;
    }

    return true;
}

static bool my_rfid_keys_read_full_file(File* file, uint8_t* buffer, size_t size) {
    size_t offset = 0;

    while(offset < size) {
        const size_t bytes_read = storage_file_read(file, buffer + offset, size - offset);
        if(bytes_read == 0) {
            return false;
        }

        offset += bytes_read;
    }

    return true;
}

static void my_rfid_keys_derive_aes_key(
    const char* password,
    const uint8_t iv[MY_RFID_KEYS_AES_IV_SIZE],
    uint8_t key[32]) {
    uint64_t hash[4] = {
        1469598103934665603ULL,
        1099511628211ULL,
        0x9e3779b97f4a7c15ULL,
        0xbf58476d1ce4e5b9ULL};

    for(size_t lane = 0; lane < COUNT_OF(hash); lane++) {
        hash[lane] ^= lane;

        for(const char* cursor = password; *cursor; cursor++) {
            hash[lane] ^= (uint8_t)*cursor;
            hash[lane] *= 1099511628211ULL;
            hash[lane] ^= hash[lane] >> 32;
        }

        for(size_t i = 0; i < MY_RFID_KEYS_AES_IV_SIZE; i++) {
            hash[lane] ^= iv[i];
            hash[lane] *= 1099511628211ULL;
            hash[lane] ^= hash[lane] >> 29;
        }

        for(size_t i = 0; i < sizeof(hash[lane]); i++) {
            key[(lane * sizeof(hash[lane])) + i] = (uint8_t)(hash[lane] >> (i * 8));
        }
    }
}

static bool my_rfid_keys_aes256_ctr_crypt(
    const char* password,
    const uint8_t iv[MY_RFID_KEYS_AES_IV_SIZE],
    const uint8_t* input,
    uint8_t* output,
    size_t size) {
    uint8_t key[32];
    bool success;

    my_rfid_keys_derive_aes_key(password, iv, key);
    success = furi_hal_crypto_ctr(key, iv, input, output, size);
    memset(key, 0, sizeof(key));

    return success;
}

static bool my_rfid_keys_encrypt_file(
    Storage* storage,
    const char* source_path,
    const char* encrypted_path,
    const char* password) {
    bool success = false;
    File* source = storage_file_alloc(storage);
    File* encrypted = storage_file_alloc(storage);
    uint8_t iv[MY_RFID_KEYS_AES_IV_SIZE];
    uint8_t* plaintext = NULL;
    uint8_t* ciphertext = NULL;
    size_t file_size = 0;
    bool source_open = false;
    bool encrypted_open = false;

    if(!storage_file_open(source, source_path, FSAM_READ, FSOM_OPEN_EXISTING)) {
        FURI_LOG_E(TAG, "Failed to open plaintext temp file");
        goto cleanup;
    }
    source_open = true;

    const uint64_t source_size = storage_file_size(source);
    if(source_size == 0 || source_size > MY_RFID_KEYS_MAX_FILE_SIZE) {
        FURI_LOG_E(TAG, "Plaintext temp file size is invalid");
        goto cleanup;
    }

    file_size = (size_t)source_size;
    plaintext = malloc(file_size);
    ciphertext = malloc(file_size);
    if(!plaintext || !ciphertext) {
        FURI_LOG_E(TAG, "Failed to allocate encryption buffers");
        goto cleanup;
    }

    if(!my_rfid_keys_read_full_file(source, plaintext, file_size)) {
        FURI_LOG_E(TAG, "Failed to read plaintext temp file");
        goto cleanup;
    }

    furi_hal_random_fill_buf(iv, sizeof(iv));
    if(!my_rfid_keys_aes256_ctr_crypt(password, iv, plaintext, ciphertext, file_size)) {
        FURI_LOG_E(TAG, "AES-256 encryption failed");
        goto cleanup;
    }

    if(!storage_file_open(encrypted, encrypted_path, FSAM_WRITE, FSOM_CREATE_ALWAYS)) {
        FURI_LOG_E(TAG, "Failed to create encrypted file");
        goto cleanup;
    }
    encrypted_open = true;

    if(storage_file_write(encrypted, MY_RFID_KEYS_ENCRYPTED_MAGIC, 4) != 4) goto cleanup;
    if(storage_file_write(encrypted, iv, sizeof(iv)) != sizeof(iv)) goto cleanup;
    if(storage_file_write(encrypted, ciphertext, file_size) != file_size) goto cleanup;
    success = true;

cleanup:
    if(plaintext) {
        memset(plaintext, 0, file_size);
        free(plaintext);
    }
    if(ciphertext) {
        memset(ciphertext, 0, file_size);
        free(ciphertext);
    }
    if(encrypted_open) storage_file_close(encrypted);
    if(source_open) storage_file_close(source);
    storage_file_free(encrypted);
    storage_file_free(source);
    storage_common_remove(storage, source_path);
    if(!success) storage_common_remove(storage, encrypted_path);

    return success;
}

static bool my_rfid_keys_decrypt_file(
    Storage* storage,
    const char* encrypted_path,
    const char* output_path,
    const char* password) {
    bool success = false;
    File* encrypted = storage_file_alloc(storage);
    File* output = storage_file_alloc(storage);
    uint8_t iv[MY_RFID_KEYS_AES_IV_SIZE];
    uint8_t* ciphertext = NULL;
    uint8_t* plaintext = NULL;
    size_t payload_size = 0;
    char magic[4];
    bool encrypted_open = false;
    bool output_open = false;

    if(!storage_file_open(encrypted, encrypted_path, FSAM_READ, FSOM_OPEN_EXISTING)) {
        FURI_LOG_E(TAG, "Failed to open encrypted file");
        goto cleanup;
    }
    encrypted_open = true;

    if(storage_file_read(encrypted, magic, sizeof(magic)) != sizeof(magic) ||
       memcmp(magic, MY_RFID_KEYS_ENCRYPTED_MAGIC, sizeof(magic)) != 0 ||
       storage_file_read(encrypted, iv, sizeof(iv)) != sizeof(iv)) {
        FURI_LOG_E(TAG, "Encrypted file header is invalid");
        goto cleanup;
    }

    const uint64_t encrypted_size = storage_file_size(encrypted);
    if(encrypted_size <= sizeof(magic) + sizeof(iv) ||
       encrypted_size > sizeof(magic) + sizeof(iv) + MY_RFID_KEYS_MAX_FILE_SIZE) {
        FURI_LOG_E(TAG, "Encrypted file size is invalid");
        goto cleanup;
    }

    payload_size = (size_t)(encrypted_size - sizeof(magic) - sizeof(iv));
    ciphertext = malloc(payload_size);
    plaintext = malloc(payload_size);
    if(!ciphertext || !plaintext) {
        FURI_LOG_E(TAG, "Failed to allocate decryption buffers");
        goto cleanup;
    }

    if(!my_rfid_keys_read_full_file(encrypted, ciphertext, payload_size)) {
        FURI_LOG_E(TAG, "Failed to read encrypted payload");
        goto cleanup;
    }

    if(!my_rfid_keys_aes256_ctr_crypt(password, iv, ciphertext, plaintext, payload_size)) {
        FURI_LOG_E(TAG, "AES-256 decryption failed");
        goto cleanup;
    }

    if(!storage_file_open(output, output_path, FSAM_WRITE, FSOM_CREATE_ALWAYS)) {
        FURI_LOG_E(TAG, "Failed to create decrypted temp file");
        goto cleanup;
    }
    output_open = true;

    if(storage_file_write(output, plaintext, payload_size) != payload_size) goto cleanup;
    success = true;

cleanup:
    if(ciphertext) {
        memset(ciphertext, 0, payload_size);
        free(ciphertext);
    }
    if(plaintext) {
        memset(plaintext, 0, payload_size);
        free(plaintext);
    }
    if(output_open) storage_file_close(output);
    if(encrypted_open) storage_file_close(encrypted);
    storage_file_free(output);
    storage_file_free(encrypted);
    if(!success) storage_common_remove(storage, output_path);

    return success;
}

static void my_rfid_keys_emulate_loaded(
    MyRfidKeysApp* app,
    LFRFIDWorker* worker,
    ProtocolDict* dict,
    ProtocolId protocol,
    View* view) {
    UNUSED(view);
    furi_string_printf(app->line_1, "Emulating %s", protocol_dict_get_name(dict, protocol));
    protocol_dict_render_uid(dict, app->line_2, protocol);
    app->state = MyRfidKeysViewEmulating;
    my_rfid_keys_view_update(app);

    lfrfid_worker_start_thread(worker);
    lfrfid_worker_emulate_start(worker, protocol);
    my_rfid_keys_wait_for_exit(app);
    lfrfid_worker_stop(worker);
    lfrfid_worker_stop_thread(worker);
}

static bool my_rfid_keys_select_key_file(
    MyRfidKeysApp* app,
    DialogsApp* dialogs,
    Storage* storage,
    FuriString* result_path,
    MyRfidKeysViewState state) {
    FuriString* path = furi_string_alloc_set(MY_RFID_KEYS_FOLDER);
    DialogsFileBrowserOptions browser_options;

    app->state = state;
    if(state == MyRfidKeysViewDeleting) {
        furi_string_set(app->line_1, "Delete Key");
    } else {
        furi_string_set(app->line_1, "Open File");
    }
    furi_string_set(app->line_2, "Choose an .erfid file");
    my_rfid_keys_view_update(app);

    my_rfid_keys_ensure_folder(storage);
    dialog_file_browser_set_basic_options(&browser_options, ".erfid", NULL);
    browser_options.base_path = MY_RFID_KEYS_FOLDER;
    browser_options.hide_dot_files = true;
    browser_options.skip_assets = true;

    view_holder_send_to_back(app->view_holder);
    const bool selected = dialog_file_browser_show(dialogs, result_path, path, &browser_options);
    view_holder_send_to_front(app->view_holder);
    furi_delay_ms(250);
    my_rfid_keys_flush_input(app);
    furi_string_free(path);

    return selected;
}

static bool my_rfid_keys_confirm_delete(MyRfidKeysApp* app) {
    InputEvent event;

    app->state = MyRfidKeysViewConfirmDelete;
    my_rfid_keys_view_update(app);

    while(true) {
        if(furi_message_queue_get(app->input_queue, &event, FuriWaitForever) != FuriStatusOk) {
            continue;
        }

        if(!my_rfid_keys_is_button_press(&event)) {
            continue;
        }

        if(event.key == InputKeyLeft || event.key == InputKeyBack) {
            return false;
        } else if(event.key == InputKeyRight) {
            return true;
        }
    }
}

static void my_rfid_keys_open_file(
    MyRfidKeysApp* app,
    Gui* gui,
    View* view,
    Storage* storage,
    DialogsApp* dialogs,
    ProtocolDict* dict) {
    UNUSED(view);
    UNUSED(gui);
    FuriString* result_path = furi_string_alloc();
    FuriString* temp_path = furi_string_alloc();

    if(!my_rfid_keys_select_key_file(
           app, dialogs, storage, result_path, MyRfidKeysViewOpening)) {
        app->state = MyRfidKeysViewMenu;
        goto cleanup;
    }

    my_rfid_keys_build_filename(temp_path, "open.tmp");
    if(!my_rfid_keys_ask_password(app, app->main_view)) {
        FURI_LOG_I(TAG, "Password prompt cancelled");
        goto cleanup;
    }

    my_rfid_keys_show_working(app, "Opening", furi_string_get_cstr(result_path));

    if(!my_rfid_keys_decrypt_file(
           storage,
           furi_string_get_cstr(result_path),
           furi_string_get_cstr(temp_path),
           app->password)) {
        app->state = MyRfidKeysViewSaveError;
        furi_string_set(app->line_1, "Open Failed");
        furi_string_set(app->line_2, "Decrypt error");
        goto cleanup;
    }

    app->loaded_protocol = lfrfid_dict_file_load(dict, furi_string_get_cstr(temp_path));
    if(app->loaded_protocol == PROTOCOL_NO) {
        app->state = MyRfidKeysViewSaveError;
        furi_string_set(app->line_1, "Open Failed");
        furi_string_set(app->line_2, "Wrong password or file");
        goto cleanup;
    }

    FURI_LOG_I(
        TAG,
        "Loaded encrypted RFID file: %s",
        furi_string_get_cstr(result_path));

    app->file_open = true;
    my_rfid_keys_show_done(app, "Opened", furi_string_get_cstr(result_path));
    my_rfid_keys_view_update(app);
    furi_delay_ms(MY_RFID_KEYS_SUCCESS_MS);
    my_rfid_keys_flush_input(app);
    app->state = MyRfidKeysViewMenu;

cleanup:
    memset(app->password, 0, sizeof(app->password));
    storage_common_remove(storage, furi_string_get_cstr(temp_path));
    if(app->state != MyRfidKeysViewMenu) {
        my_rfid_keys_view_update(app);
    }
    furi_string_free(temp_path);
    furi_string_free(result_path);
}

static bool my_rfid_keys_verify_file_password(
    MyRfidKeysApp* app,
    Storage* storage,
    ProtocolDict* dict,
    const char* encrypted_path,
    const char* temp_path) {
    if(!my_rfid_keys_decrypt_file(storage, encrypted_path, temp_path, app->password)) {
        return false;
    }

    return lfrfid_dict_file_load(dict, temp_path) != PROTOCOL_NO;
}

static void my_rfid_keys_delete_key(
    MyRfidKeysApp* app,
    Gui* gui,
    View* view,
    Storage* storage,
    DialogsApp* dialogs,
    ProtocolDict* dict) {
    UNUSED(gui);
    UNUSED(view);
    FuriString* result_path = furi_string_alloc();
    FuriString* temp_path = furi_string_alloc();
    bool password_ok = false;

    if(!my_rfid_keys_select_key_file(
           app, dialogs, storage, result_path, MyRfidKeysViewDeleting)) {
        app->state = MyRfidKeysViewMenu;
        goto cleanup;
    }

    my_rfid_keys_build_filename(temp_path, "delete.tmp");
    for(uint8_t attempt = 0; attempt < 3; attempt++) {
        if(!my_rfid_keys_ask_text(
               app,
               app->main_view,
               MyRfidKeysViewPassword,
               "Password",
               app->password,
               sizeof(app->password))) {
            goto cleanup;
        }

        if(my_rfid_keys_verify_file_password(
               app,
               storage,
               dict,
               furi_string_get_cstr(result_path),
               furi_string_get_cstr(temp_path))) {
            password_ok = true;
            break;
        }

        memset(app->password, 0, sizeof(app->password));
        storage_common_remove(storage, furi_string_get_cstr(temp_path));
        app->state = MyRfidKeysViewSaveError;
        furi_string_set(app->line_1, "Wrong Password");
        if(attempt < 2) {
            furi_string_printf(app->line_2, "%u tries left", (unsigned int)(2 - attempt));
            my_rfid_keys_view_update(app);
            furi_delay_ms(1200);
        } else {
            furi_string_set(app->line_2, "Back to menu");
            my_rfid_keys_view_update(app);
            furi_delay_ms(1500);
        }
    }

    if(!password_ok) {
        app->state = MyRfidKeysViewMenu;
        goto cleanup;
    }

    if(!my_rfid_keys_confirm_delete(app)) {
        app->state = MyRfidKeysViewMenu;
        goto cleanup;
    }

    my_rfid_keys_show_working(app, "Deleting", furi_string_get_cstr(result_path));

    if(storage_common_remove(storage, furi_string_get_cstr(result_path)) == FSE_OK) {
        my_rfid_keys_show_done(app, "Deleted", furi_string_get_cstr(result_path));
    } else {
        app->state = MyRfidKeysViewSaveError;
        furi_string_set(app->line_1, "Delete Failed");
        furi_string_set(app->line_2, "Could not remove file");
    }
    my_rfid_keys_view_update(app);
    my_rfid_keys_wait_for_exit(app);

cleanup:
    memset(app->password, 0, sizeof(app->password));
    storage_common_remove(storage, furi_string_get_cstr(temp_path));
    furi_string_free(temp_path);
    furi_string_free(result_path);
}

int32_t my_rfid_keys_app(void* p) {
    UNUSED(p);

    ProtocolDict* dict = protocol_dict_alloc(lfrfid_protocols, LFRFIDProtocolMax);
    LFRFIDWorker* worker = lfrfid_worker_alloc(dict);
    FuriEventFlag* events = furi_event_flag_alloc();
    Storage* storage = furi_record_open(RECORD_STORAGE);
    Gui* gui = furi_record_open(RECORD_GUI);
    DialogsApp* dialogs = furi_record_open(RECORD_DIALOGS);
    ViewHolder* view_holder = view_holder_alloc();
    View* main_view = view_alloc();
    TextInput* text_input = text_input_alloc();
    MyRfidKeysApp app = {
        .input_queue = furi_message_queue_alloc(8, sizeof(InputEvent)),
        .line_1 = furi_string_alloc(),
        .line_2 = furi_string_alloc(),
        .events = events,
        .password = {0},
        .filename_input = {0},
        .menu_index = 0,
        .file_open = false,
        .loaded_protocol = PROTOCOL_NO,
        .state = MyRfidKeysViewSplash,
        .view_holder = view_holder,
        .main_view = main_view,
        .text_input = text_input,
    };
    MyRfidKeysReadContext read_context = {
        .events = events,
        .protocol = PROTOCOL_NO,
    };

    view_allocate_model(app.main_view, ViewModelTypeLockFree, sizeof(MyRfidKeysApp*));
    *((MyRfidKeysApp**)view_get_model(app.main_view)) = &app;
    view_commit_model(app.main_view, false);
    view_set_draw_callback(app.main_view, my_rfid_keys_draw_callback);
    view_set_input_callback(app.main_view, my_rfid_keys_input_callback);
    view_set_update_callback(app.main_view, view_holder_update);
    view_set_update_callback_context(app.main_view, app.view_holder);
    view_set_context(app.main_view, &app);
    view_holder_set_back_callback(app.view_holder, my_rfid_keys_back_callback, &app);
    view_holder_attach_to_gui(app.view_holder, gui);
    view_holder_set_view(app.view_holder, app.main_view);

    my_rfid_keys_view_update(&app);
    furi_delay_ms(MY_RFID_KEYS_SPLASH_MS);
    my_rfid_keys_flush_input(&app);

    while(true) {
        MyRfidKeysMenuItem selected_item = MyRfidKeysMenuRead;
        if(!my_rfid_keys_wait_for_menu(&app, app.main_view, &selected_item)) {
            break;
        }

        if(selected_item == MyRfidKeysMenuExit) {
            break;
        }

        if(selected_item == MyRfidKeysMenuAbout) {
            my_rfid_keys_show_about(&app);
            my_rfid_keys_flush_input(&app);
            continue;
        }

        if(selected_item == MyRfidKeysMenuClose) {
            app.file_open = false;
            app.loaded_protocol = PROTOCOL_NO;
            my_rfid_keys_flush_input(&app);
            continue;
        }

        if(selected_item == MyRfidKeysMenuEmulate) {
            my_rfid_keys_emulate_loaded(&app, worker, dict, app.loaded_protocol, app.main_view);
            my_rfid_keys_flush_input(&app);
            continue;
        }

        if(selected_item == MyRfidKeysMenuDelete) {
            my_rfid_keys_delete_key(&app, gui, app.main_view, storage, dialogs, dict);
            my_rfid_keys_flush_input(&app);
            continue;
        }

        if(selected_item == MyRfidKeysMenuOpen) {
            my_rfid_keys_open_file(&app, gui, app.main_view, storage, dialogs, dict);
            my_rfid_keys_flush_input(&app);
            continue;
        }

        FURI_LOG_I(TAG, "Scanning for LF RFID tag");
        read_context.protocol = PROTOCOL_NO;
        my_rfid_keys_flush_input(&app);
        furi_event_flag_clear(events, MY_RFID_KEYS_READ_DONE);
        lfrfid_worker_start_thread(worker);
        lfrfid_worker_read_start(
            worker, LFRFIDWorkerReadTypeAuto, my_rfid_keys_read_callback, &read_context);

        const bool read_done = my_rfid_keys_wait_for_read(&app, events, app.main_view);

        lfrfid_worker_stop(worker);
        lfrfid_worker_stop_thread(worker);

        if(read_done && (read_context.protocol != PROTOCOL_NO)) {
            FuriString* filename = furi_string_alloc();
            FuriString* temp_filename = furi_string_alloc();
            FuriString* uid = furi_string_alloc();

            app.state = MyRfidKeysViewReadSuccess;
            my_rfid_keys_view_update(&app);
            furi_delay_ms(MY_RFID_KEYS_SUCCESS_MS);
            my_rfid_keys_flush_input(&app);

            my_rfid_keys_build_filename(temp_filename, "tmp");
            protocol_dict_render_uid(dict, uid, read_context.protocol);

            if(!my_rfid_keys_ensure_folder(storage)) {
                app.state = MyRfidKeysViewSaveError;
                furi_string_set(app.line_1, "Save Failed");
                furi_string_set(app.line_2, "Could not create folder");
                FURI_LOG_E(TAG, "Unable to create save folder: %s", MY_RFID_KEYS_FOLDER);
            } else if(!my_rfid_keys_ask_filename(&app, app.main_view, filename)) {
                FURI_LOG_I(TAG, "Filename prompt cancelled");
            } else if(!my_rfid_keys_ask_password(&app, app.main_view)) {
                FURI_LOG_I(TAG, "Password prompt cancelled");
            } else {
                my_rfid_keys_show_working(&app, "Saving", furi_string_get_cstr(filename));
                if(lfrfid_dict_file_save(
                       dict, read_context.protocol, furi_string_get_cstr(temp_filename)) &&
                   my_rfid_keys_encrypt_file(
                       storage,
                       furi_string_get_cstr(temp_filename),
                       furi_string_get_cstr(filename),
                       app.password)) {
                    app.file_open = true;
                    app.loaded_protocol = read_context.protocol;
                    my_rfid_keys_show_done(&app, "Saved", furi_string_get_cstr(filename));
                    my_rfid_keys_view_update(&app);
                    furi_delay_ms(MY_RFID_KEYS_SUCCESS_MS);
                    my_rfid_keys_flush_input(&app);
                    app.state = MyRfidKeysViewMenu;
                    FURI_LOG_I(
                        TAG,
                        "Encrypted %s tag %s to %s",
                        protocol_dict_get_name(dict, read_context.protocol),
                        furi_string_get_cstr(uid),
                        furi_string_get_cstr(filename));
                } else {
                    app.state = MyRfidKeysViewSaveError;
                    furi_string_set(app.line_1, "Save Failed");
                    furi_string_set(app.line_2, "Encrypt/write error");
                    FURI_LOG_E(
                        TAG, "Failed to encrypt RFID tag to %s", furi_string_get_cstr(filename));
                }
            }

            memset(app.password, 0, sizeof(app.password));
            storage_common_remove(storage, furi_string_get_cstr(temp_filename));
            furi_string_free(uid);
            furi_string_free(temp_filename);
            furi_string_free(filename);
        } else if(app.state == MyRfidKeysViewScanning) {
            app.state = MyRfidKeysViewTimeout;
            furi_string_set(app.line_1, "No Tag Found");
            furi_string_set(app.line_2, "Scan timed out");
            FURI_LOG_W(TAG, "No LF RFID tag read before timeout");
        }

        if(app.state != MyRfidKeysViewCancelled && app.state != MyRfidKeysViewMenu) {
            my_rfid_keys_view_update(&app);
            my_rfid_keys_wait_for_exit(&app);
        }
        my_rfid_keys_flush_input(&app);
    }

    view_holder_set_view(app.view_holder, NULL);
    view_free_model(app.main_view);
    view_free(app.main_view);
    text_input_free(app.text_input);
    view_holder_free(app.view_holder);
    furi_string_free(app.line_2);
    furi_string_free(app.line_1);
    furi_message_queue_free(app.input_queue);
    furi_record_close(RECORD_DIALOGS);
    furi_record_close(RECORD_GUI);
    furi_record_close(RECORD_STORAGE);
    furi_event_flag_free(events);
    lfrfid_worker_free(worker);
    protocol_dict_free(dict);

    return 0;
}
